In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
automobiles_data = pd.read_csv('../datasets/CarPrice_Assignment.csv')

automobiles_data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
automobiles_data.shape

(205, 26)

In [4]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [6]:
automobiles_data = pd.get_dummies(automobiles_data)

In [7]:
automobiles_data.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [8]:
automobiles_data.shape

(205, 52)

In [9]:
X = automobiles_data.drop('price', axis=1)

Y = automobiles_data['price']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [11]:
x_train.shape, x_test.shape

((164, 51), (41, 51))

In [12]:
y_train.shape, y_test.shape

((164,), (41,))

In [13]:
model = LinearRegression().fit(x_train, y_train)

In [14]:
Training_score = model.score(x_train, y_train)

Training_score

0.9340501895107627

In [15]:
y_pred = model.predict(x_test)

y_pred

array([21843.81844213,  7225.97055464, 33184.7031964 ,  5890.41379847,
       12282.43645745, 18226.7479401 , 10861.22208105, 10312.42434302,
        5638.07491136, 20890.36643411, 11908.03644204,  6300.31176914,
       10090.40884196,  7818.73088621,  6066.19397537, 10223.57578222,
       15630.51393205, 20416.61210446, 22695.68603733,  9387.36245256,
        5809.26434427,  9694.59932037, 13774.88590006,  8962.02297328,
        6810.42299738,  5967.58398354,  9048.59273184,  8400.8178032 ,
        6889.24586085,  5923.30660108, 38827.28599849, 36495.13241299,
        9906.92704087,  6343.50078011, 11620.15419621,  7493.45610771,
        6592.42411967,  8871.3932005 ,  9255.39196098,  7411.14996123,
       21296.66841518])

In [16]:
Testing_score = r2_score(y_test, y_pred)

Testing_score

0.9270868605893767

In [17]:
import json

In [18]:
model.coef_

array([ 7.55355929e+01, -4.47347797e+01,  6.45800929e+02, -4.84425641e+01,
        5.02541702e+00,  7.65111950e+01, -8.03651132e+02, -4.24122267e+03,
       -1.49424769e+03,  1.98499460e+01,  2.01737172e+00, -1.74935680e+02,
        2.51912657e+02,  7.32141632e+03, -7.32141632e+03, -7.15864645e+02,
        7.15864645e+02, -2.11406198e+02,  2.11406198e+02,  2.79270365e+03,
       -1.37041530e+03, -7.11446889e+02,  1.31392125e+02, -8.42233578e+02,
       -3.01096165e+02, -3.19615133e+02,  6.20711298e+02, -4.47259431e+03,
        4.47259431e+03,  1.65867540e+03, -5.97458909e+03, -2.43008711e+02,
        4.64556009e+03,  2.23758120e+03, -4.24625662e+03,  1.92203773e+03,
        4.81262339e+03, -4.51963391e+03, -5.76014411e+03, -8.67403517e+02,
        3.97048701e+03,  4.42033411e+02,  1.92203773e+03,  9.69711019e+02,
        5.36683566e+02, -9.10878371e+02,  7.32141632e+03, -4.11551324e+03,
        2.33689334e+02, -4.03510863e+03,  0.00000000e+00])

In [19]:
model.intercept_

-21644.459276153488

In [25]:
model_param = {}

model_param['coef'] = list(model.coef_)
model_param['intercept'] = model.intercept_.tolist()

In [26]:
model_param

{'coef': [75.53559289572794,
  -44.73477965963104,
  645.8009285734116,
  -48.44256409219746,
  5.025417018740718,
  76.51119500771773,
  -803.6511324935046,
  -4241.2226653446,
  -1494.2476883840413,
  19.849946033502825,
  2.017371718649212,
  -174.9356798813846,
  251.91265653975518,
  7321.4163160039325,
  -7321.4163160039325,
  -715.8646452372417,
  715.8646452371773,
  -211.40619832437702,
  211.40619832439336,
  2792.703645245359,
  -1370.4153030497223,
  -711.4468891534146,
  131.39212469014294,
  -842.2335777324032,
  -301.09616499333634,
  -319.6151331109544,
  620.7112981042934,
  -4472.594311930589,
  4472.594311930573,
  1658.6753993179555,
  -5974.589088343082,
  -243.00871051154567,
  4645.560088040208,
  2237.5811977902176,
  -4246.2566165355665,
  1922.0377302418765,
  4812.623390585098,
  -4519.633907811252,
  -5760.144114437164,
  -867.4035170888822,
  3970.487007837294,
  442.03341067295156,
  1922.037730241881,
  969.711019233733,
  536.6835655997625,
  -910.878370

In [28]:
json_txt = json.dumps(model_param, indent=4)

json_txt

'{\n    "coef": [\n        75.53559289572794,\n        -44.73477965963104,\n        645.8009285734116,\n        -48.44256409219746,\n        5.025417018740718,\n        76.51119500771773,\n        -803.6511324935046,\n        -4241.2226653446,\n        -1494.2476883840413,\n        19.849946033502825,\n        2.017371718649212,\n        -174.9356798813846,\n        251.91265653975518,\n        7321.4163160039325,\n        -7321.4163160039325,\n        -715.8646452372417,\n        715.8646452371773,\n        -211.40619832437702,\n        211.40619832439336,\n        2792.703645245359,\n        -1370.4153030497223,\n        -711.4468891534146,\n        131.39212469014294,\n        -842.2335777324032,\n        -301.09616499333634,\n        -319.6151331109544,\n        620.7112981042934,\n        -4472.594311930589,\n        4472.594311930573,\n        1658.6753993179555,\n        -5974.589088343082,\n        -243.00871051154567,\n        4645.560088040208,\n        2237.5811977902176,\n 

In [29]:
with open('models/regressor_param.txt', 'w') as file:
    
    file.write(json_txt)

In [30]:
with open('models/regressor_param.txt', 'r') as file:
    
    json_text=json.load(file)

In [31]:
json_model = LinearRegression()

In [32]:
json_text['coef']

[75.53559289572794,
 -44.73477965963104,
 645.8009285734116,
 -48.44256409219746,
 5.025417018740718,
 76.51119500771773,
 -803.6511324935046,
 -4241.2226653446,
 -1494.2476883840413,
 19.849946033502825,
 2.017371718649212,
 -174.9356798813846,
 251.91265653975518,
 7321.4163160039325,
 -7321.4163160039325,
 -715.8646452372417,
 715.8646452371773,
 -211.40619832437702,
 211.40619832439336,
 2792.703645245359,
 -1370.4153030497223,
 -711.4468891534146,
 131.39212469014294,
 -842.2335777324032,
 -301.09616499333634,
 -319.6151331109544,
 620.7112981042934,
 -4472.594311930589,
 4472.594311930573,
 1658.6753993179555,
 -5974.589088343082,
 -243.00871051154567,
 4645.560088040208,
 2237.5811977902176,
 -4246.2566165355665,
 1922.0377302418765,
 4812.623390585098,
 -4519.633907811252,
 -5760.144114437164,
 -867.4035170888822,
 3970.487007837294,
 442.03341067295156,
 1922.037730241881,
 969.711019233733,
 536.6835655997625,
 -910.8783709088784,
 7321.416316003939,
 -4115.513237140323,
 233

In [33]:
json_text['intercept']

-21644.459276153488

In [34]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [35]:
y_pred = json_model.predict(x_test)

r2_score(y_test, y_pred)

0.9270868605893767

In [36]:
Testing_score

0.9270868605893767

In [37]:
import pickle

In [38]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [39]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [40]:
y_pred = pickle_model.predict(x_test)

y_pred

array([21843.81844213,  7225.97055464, 33184.7031964 ,  5890.41379847,
       12282.43645745, 18226.7479401 , 10861.22208105, 10312.42434302,
        5638.07491136, 20890.36643411, 11908.03644204,  6300.31176914,
       10090.40884196,  7818.73088621,  6066.19397537, 10223.57578222,
       15630.51393205, 20416.61210446, 22695.68603733,  9387.36245256,
        5809.26434427,  9694.59932037, 13774.88590006,  8962.02297328,
        6810.42299738,  5967.58398354,  9048.59273184,  8400.8178032 ,
        6889.24586085,  5923.30660108, 38827.28599849, 36495.13241299,
        9906.92704087,  6343.50078011, 11620.15419621,  7493.45610771,
        6592.42411967,  8871.3932005 ,  9255.39196098,  7411.14996123,
       21296.66841518])

In [41]:
r2_score(y_test, y_pred)

0.9270868605893767

In [42]:
Testing_score

0.9270868605893767

In [43]:
import joblib

In [44]:
filename = 'models/model.joblib'

In [45]:
joblib.dump(model, filename)

['models/model.joblib']

In [47]:
joblib_model = joblib.load(filename)

In [48]:
y_pred = joblib_model.predict(x_test)

y_pred

array([21843.81844213,  7225.97055464, 33184.7031964 ,  5890.41379847,
       12282.43645745, 18226.7479401 , 10861.22208105, 10312.42434302,
        5638.07491136, 20890.36643411, 11908.03644204,  6300.31176914,
       10090.40884196,  7818.73088621,  6066.19397537, 10223.57578222,
       15630.51393205, 20416.61210446, 22695.68603733,  9387.36245256,
        5809.26434427,  9694.59932037, 13774.88590006,  8962.02297328,
        6810.42299738,  5967.58398354,  9048.59273184,  8400.8178032 ,
        6889.24586085,  5923.30660108, 38827.28599849, 36495.13241299,
        9906.92704087,  6343.50078011, 11620.15419621,  7493.45610771,
        6592.42411967,  8871.3932005 ,  9255.39196098,  7411.14996123,
       21296.66841518])

In [49]:
r2_score(y_test, y_pred)

0.9270868605893767

In [50]:
Testing_score

0.9270868605893767